"""Structured LLM output schemas for the Planning Agent (Milestone 3 §6/§13).

Each schema that's generated by `PlanningProvider.generate_structured`
carries an `offline_default(prompt: str) -> Self` classmethod — the
fallback `TemplatePlanningProvider` (infrastructure/llm/template_planning.py)
calls this via duck typing when no LLM is configured, keeping CI and the
planning graph's unit tests fully functional. Defaults are deliberately
conservative (empty citation/affected-file lists, low confidence) rather
than inventive — an offline default that claimed things about the
repository it never looked at would itself be a hallucination.
"""

from pydantic import BaseModel, Field


class IssueAnalysis(BaseModel):
    """Output of the `analyze_issue` node (Milestone 3 §7)."""

    problem: str
    desired_behavior: str
    functional_requirements: list[str] = Field(default_factory=list)
    technical_requirements: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    acceptance_criteria: list[str] = Field(default_factory=list)
    ambiguities: list[str] = Field(default_factory=list)
    potentially_affected_components: list[str] = Field(default_factory=list)

    @classmethod
    def offline_default(cls, prompt: str) -> "IssueAnalysis":
        return cls(
            problem=f"(offline template — no LLM configured) {prompt[:300]}",
            desired_behavior="Unknown — requires an LLM-backed PlanningProvider to analyze.",
            ambiguities=["Issue was not analyzed by a language model (template provider active)."],
        )


class SearchQueries(BaseModel):
    """Output of the `generate_search_queries` node (Milestone 3 §8)."""

    queries: list[str] = Field(min_length=1, max_length=8)

    @classmethod
    def offline_default(cls, prompt: str) -> "SearchQueries":
        first_line = next((line.strip() for line in prompt.splitlines() if line.strip()), "issue")
        return cls(queries=[first_line[:200]])


class Citation(BaseModel):
    file_path: str
    start_line: int
    end_line: int
    claim: str


class ImplementationStep(BaseModel):
    step_number: int
    description: str
    affected_files: list[str] = Field(default_factory=list)
    affected_symbols: list[str] = Field(default_factory=list)
    reason: str
    depends_on_steps: list[int] = Field(default_factory=list)
    verification_method: str


class ImplementationPlan(BaseModel):
    """Output of the `generate_plan` node (Milestone 3 §13) — the
    structured plan presented for human review."""

    summary: str
    understanding: str
    affected_files: list[str] = Field(default_factory=list)
    affected_components: list[str] = Field(default_factory=list)
    implementation_steps: list[ImplementationStep] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    database_changes: list[str] = Field(default_factory=list)
    api_changes: list[str] = Field(default_factory=list)
    frontend_changes: list[str] = Field(default_factory=list)
    testing_strategy: str = ""
    security_considerations: list[str] = Field(default_factory=list)
    performance_considerations: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    acceptance_criteria: list[str] = Field(default_factory=list)
    citations: list[Citation] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)

    @classmethod
    def offline_default(cls, prompt: str) -> "ImplementationPlan":
        return cls(
            summary="Offline template plan — no LLM configured, review manually.",
            understanding=(
                "PLANNING_PROVIDER=template is active, so no language model analyzed this "
                "issue or the retrieved repository context. This plan intentionally makes no "
                "claims about repository structure to avoid fabricating citations."
            ),
            testing_strategy="Not determined — requires an LLM-backed PlanningProvider.",
            risks=["Generated without LLM assistance — treat as a placeholder, not a real plan."],
            assumptions=["No structured LLM was available at generation time."],
            confidence=0.1,
        )
