"""add repositories, indexed_files, chunks

Revision ID: 2308ec89d829
Revises: 
Create Date: 2026-08-07 22:33:12.854476

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2308ec89d829'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_indexed_commit', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('indexed_file_count', sa.Integer(), nullable=False),
    sa.Column('indexed_chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('indexed_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'path', name='uq_indexed_file_path')
    )
    op.create_index(op.f('ix_indexed_files_repository_id'), 'indexed_files', ['repository_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=512), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['indexed_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunk_repository_content_hash', 'chunks', ['repository_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_chunks_file_id'), 'chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_chunks_repository_id'), 'chunks', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_repository_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_file_id'), table_name='chunks')
    op.drop_index('ix_chunk_repository_content_hash', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_indexed_files_repository_id'), table_name='indexed_files')
    op.drop_table('indexed_files')
    op.drop_table('repositories')
    # ### end Alembic commands ###
